blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<int:id>', views.post_detail, name='post_detail'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Managers
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = Post.Status.PUBLISHED)

# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        REJECTED = 'RJ', 'Rejected'

    # relation
    author = models.ForeignKey(User, on_delete=models.CASCADE , related_name='user_posts')
    #data fields
    title = models.CharField(max_length=250)
    description = models.TextField()
    slug = models.SlugField(max_length=250, unique=True)
    #date
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # choice fields
    status = models.CharField(max_length=2 , choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['publish'])]

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse , Http404
from .models import Post

# Create your views here.
def index(request):
    return HttpResponse('index')

def post_list(request):
    posts = Post.published.all()
    context = {
        'posts' : posts,
    }
    return render(request, "blog/list.html", context)

def post_detail(request ,id):
    try:
        post = Post.published.get(id=id)
    except:
        raise Http404("No post found")
    context = {
        'post': post,
    }
    return render(request, "blog/detail.html", context)

blog/templates/blog/detail.html
{% extends "parent/base.html" %}
{% block title %}post detail{% endblock %}
{% block content %}
    <h1>post detail</h1>
        <h2>
             {{ post.title }} by {{ post.author }}
        </h2>
    <p>{{ post.description | linebreaks}}</p>
    <p>{{ post.publish }}</p>
{% endblock %}

blog/templates/blog/list.html
{% extends "parent/base.html" %}
{% block title %}post list{% endblock %}
{% block content %}
    <h1>post list</h1>
    {% for post in posts %}
        <h2>
            <a href="{% url 'blog:post_detail' post.id %}"> {{ post.title }} </a>
        </h2>
        <p>{{ post.description | truncatewords:2}}</p>
            {% endfor %}
{% endblock %}

blog/templates/parent/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
{% include "partials/header.html" %}
{% include "partials/navigation.html" %}
{% block content %}{% endblock %}
{% include "partials/footer.html" %}
</body>
</html>

blog/templates/partials/footer.html
<p>footer</p>

blog/templates/partials/header.html
<p>header</p>

blog/templates/partials/navigation.html
<p>navigation</p>